name: Pygmalion Ping Check

on:
  schedule:
    - cron: '*/15 * * * *' # Запуск каждые 15 минут
  workflow_dispatch: # Чтобы ты мог запустить его кнопкой

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Ping Script
        run: python ping_check.py  # Название твоего файла должно быть именно таким
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add status.json
          git commit -m "Update status.json" || echo "No changes to commit"
          git push
